version: '3'
services:
  wordpress:
    image: gcr.io/digital-ucdavis-edu/main-wp-website:sandbox
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-8000}:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', '${SERVER_URL}' );
        define('WP_HOME', '${SERVER_URL}' );
        define('FORCE_SSL_ADMIN', true);
    volumes:
      - uploads-data:/var/www/html/wp-content/uploads

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL:http://elasticsearch:9200
      - xpack.security.enabled=false
      - telemetry.enabled=false
    depends_on:
      - elasticsearch

  init:
    image: gcr.io/digital-ucdavis-edu/main-wp-website-init:sandbox
    env_file:
      - .env
    environment:
      BACKUP_ENV: ${BACKUP_ENV:-sandbox}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      HOST_PORT: ${HOST_PORT:-8000}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      GOOGLE_APPLICATION_CREDENTIALS: /etc/main-website-content-reader-key.json
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./main-website-content-reader-key.json:/etc/main-website-content-reader-key.json
    # command: bash -c "tail -f /dev/null"

  indexer:
    image: gcr.io/digital-ucdavis-edu/main-wp-website-es-indexer:sandbox
    env_file:
      - .env
    ports:
      - ${INDEXER_HOST_PORT:-8000}:3000
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/main-website-content-writer-key.json
    depends_on:
      - elasticsearch
    volumes:
      - ./main-website-content-writer-key.json:/etc/main-website-content-writer-key.json

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  uploads-data:
  es-data:
