#! /bin/bash


##
# Container
##


# Container Images
WEBSITE_IMAGE_NAME=$CONTAINER_REG_ORG/main-wp-website
UTILS_IMAGE_NAME=$CONTAINER_REG_ORG/main-wp-website-utils
INDEXER_IMAGE_NAME=$CONTAINER_REG_ORG/main-wp-website-es-indexer
MYSQL_IMAGE_NAME=mysql
ADMINER_IMAGE_NAME=adminer
ELASTIC_SEARCH_IMAGE_NAME=docker.elastic.co/elasticsearch/elasticsearch
KIBANA_IMAGE_NAME=docker.elastic.co/kibana/kibana

WEBSITE_IMAGE_NAME_TAG=$WEBSITE_IMAGE_NAME:$WEBSITE_TAG
INDEXER_IMAGE_NAME_TAG=$INDEXER_IMAGE_NAME:$WEBSITE_TAG
MYSQL_IMAGE_NAME_TAG=$MYSQL_IMAGE_NAME:$MYSQL_TAG
ADMINER_IMAGE_NAME_TAG=$ADMINER_IMAGE_NAME:$ADMINER_TAG
UTILS_IMAGE_NAME_TAG=$UTILS_IMAGE_NAME:$WEBSITE_TAG
MONITORING_IMAGE_NAME_TAG=$MONITORING_IMAGE_NAME:$WEBSITE_TAG

ALL_DOCKER_BUILD_IMAGES=( $WEBSITE_IMAGE_NAME $UTILS_IMAGE_NAME $INDEXER_IMAGE_NAME )

ALL_DOCKER_BUILD_IMAGE_TAGS=(
  $WEBSITE_IMAGE_NAME_TAG
  $UTILS_IMAGE_NAME_TAG
  $INDEXER_IMAGE_NAME_TAG
)


# NPM
NPM=npm
NPM_PRIVATE_PACKAGES=(
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$THEME_REPO_NAME/src/public
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$THEME_REPO_NAME/src/editor
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-assets/src/public
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-assets/src/editor
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-locations/src/public
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-locations/src/editor
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-migration/src/editor
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-search/src/public
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-directory/src/editor
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-directory/src/public
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-special/src/editor
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-special/src/public
)
JS_BUNDLES=(
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-assets/src/public
  $REPOSITORY_DIR/$WEBSITE_REPO_NAME/$PLUGIN_REPO_NAME/ucdlib-assets/src/editor
)
