version: '3'
services:
  wordpress:
    image: {{WEBSITE_IMAGE_NAME}}:{{WEBSITE_TAG}}
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      UCD_THEME_ENV: ${UCD_THEME_ENV:-dev}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      UCD_CAS_HOST: ${UCD_CAS_HOST:-ssodev.ucdavis.edu}
    volumes:
      - uploads-data:/var/www/html/wp-content/uploads
      # theme
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{THEME_REPO_NAME}}:{{WP_UCD_THEME_DIR}}
      # plugins
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucd-cas:{{WP_PLUGIN_DIR}}/ucd-cas
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-locations:{{WP_PLUGIN_DIR}}/ucdlib-locations
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-assets:{{WP_PLUGIN_DIR}}/ucdlib-assets
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-migration:{{WP_PLUGIN_DIR}}/ucdlib-migration
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-search:{{WP_PLUGIN_DIR}}/ucdlib-search
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-directory:{{WP_PLUGIN_DIR}}/ucdlib-directory

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL:http://elasticsearch:9200
      - xpack.security.enabled=false
      - telemetry.enabled=false
    depends_on:
      - elasticsearch

  init:
    image: {{INIT_IMAGE_NAME}}:{{INIT_TAG}}
    env_file:
      - .env
    environment:
      RUN_INIT: "true"
      BACKUP_ENV: ${BACKUP_ENV:-sandbox}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      HOST_PORT: ${HOST_PORT:-8000}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      GOOGLE_APPLICATION_CREDENTIALS: /etc/main-website-content-reader-key.json
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ../init/run.sh:/run.sh
      - ../main-website-content-reader-key.json:/etc/main-website-content-reader-key.json
    # command: bash -c "tail -f /dev/null"

  backup:
    image: {{INIT_IMAGE_NAME}}:{{INIT_TAG}}
    env_file:
      - .env
    environment:
      BACKUP_ENV: ${BACKUP_ENV:-localhost}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      HOST_PORT: ${HOST_PORT:-8000}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      GOOGLE_APPLICATION_CREDENTIALS: /etc/main-website-content-reader-key.json
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - backup-data:/snapshots
      - ../init/backup_entrypoint.sh:/backup_entrypoint.sh
      - ../init/backup.sh:/backup.sh
      - ../init/backup-cron:/etc/cron.d/backup 
      - ../main-website-content-writer-key.json:/etc/main-website-content-writer-key.json
    command: bash -c "tail -f /dev/null"
    # command: "/backup_entrypoint.sh"

  indexer:
    image: {{INDEXER_IMAGE_NAME}}:{{WEBSITE_TAG}}
    env_file:
      - .env
    ports:
      - 3001:3000
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/main-website-content-writer-key.json
    depends_on:
      - elasticsearch
    volumes:
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/elastic-search/lib:/service/lib
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/elastic-search/index.js:/service/index.js
      - ../main-website-content-writer-key.json:/etc/main-website-content-writer-key.json
    # command: bash -c "tail -f /dev/null"

  db:
    image: {{MYSQL_IMAGE_NAME}}:{{MYSQL_TAG}}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wordpress}
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: {{ADMINER_IMAGE_NAME}}:{{ADMINER_TAG}}
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080

volumes:
  db-data:
  uploads-data:
  es-data:
  backup-data: