version: '3'
services:
  wordpress:
    image: {{WEBSITE_IMAGE_NAME}}:{{WEBSITE_TAG}}
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
      - ${STATUS_HOST_PORT:-3002}:8080
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      WORDPRESS_DEBUG_DISPLAY: ${WORDPRESS_DEBUG_DISPLAY:-1}
      WORDPRESS_DISABLE_FATAL_ERROR_HANDLER: ${WORDPRESS_DISABLE_FATAL_ERROR_HANDLER:-1}
      UCD_CAS_HOST: ${UCD_CAS_HOST:-ssodev.ucdavis.edu}
      UCD_THEME_ENV: ${UCD_THEME_ENV:-dev}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/etc/service-account.json}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ../main-website-content-writer-key.json:/etc/service-account.json
      - uploads-data:/usr/src/wordpress/wp-content/uploads
      - wp-logs-data:/var/log/wordpress
      # theme
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{THEME_REPO_NAME}}:{{WP_UCD_THEME_DIR}}
      # plugins
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucd-cas:{{WP_PLUGIN_DIR}}/ucd-cas
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-locations:{{WP_PLUGIN_DIR}}/ucdlib-locations
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-assets:{{WP_PLUGIN_DIR}}/ucdlib-assets
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-migration:{{WP_PLUGIN_DIR}}/ucdlib-migration
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-search:{{WP_PLUGIN_DIR}}/ucdlib-search
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-directory:{{WP_PLUGIN_DIR}}/ucdlib-directory
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/{{PLUGIN_REPO_NAME}}/ucdlib-special:{{WP_PLUGIN_DIR}}/ucdlib-special
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/monitoring/status.conf:/etc/apache2/conf-available/status.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL:http://elasticsearch:9200
      - xpack.security.enabled=false
      - telemetry.enabled=false
    depends_on:
      - elasticsearch

  monitoring:
    image: {{UTILS_IMAGE_NAME}}:{{UTILS_TAG}}
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/etc/service-account.json}
    depends_on:
      - db
      - wordpress
    volumes:
      - ../utils/monitoring/monitor.sh:/util-cmds/monitor.sh
      - ../utils/monitoring/apache.js:/util-cmds/apache.js
      - ../main-website-content-writer-key.json:/etc/service-account.json
    # command: /util-cmds/tail.sh
    command: /util-cmds/monitor.sh

  init:
    image: {{UTILS_IMAGE_NAME}}:{{UTILS_TAG}}
    env_file:
      - .env
    environment:
      RUN_INIT: "true"
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      HOST_PORT: ${HOST_PORT:-8000}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/etc/service-account.json}
      SITE_TAGLINE: ${SITE_TAGLINE:-localhost}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ../utils/init.sh:/util-cmds/init.sh
      - ../main-website-content-reader-key.json:/etc/service-account.json
    # command: /util-cmds/tail.sh
    command: /util-cmds/init.sh

  backup:
    image: {{UTILS_IMAGE_NAME}}:{{UTILS_TAG}}
    env_file:
      - .env
    environment:
      BACKUP_ENV: ${BACKUP_ENV:-localhost}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      HOST_PORT: ${HOST_PORT:-8000}
      WORDPRESS_DB_DATABASE: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/etc/service-account.json}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - backup-data:/snapshots
      - ../utils/backup_entrypoint.sh:/cmds/backup_entrypoint.sh
      - ../utils/backup.sh:/cmds/backup.sh
      - ../utils/backup-cron:/etc/cron.d/backup 
      - ../main-website-content-writer-key.json:/etc/service-account.json
    command: /util-cmds/tail.sh
    # command: "/util-cmds/backup_entrypoint.sh"

  indexer:
    image: {{INDEXER_IMAGE_NAME}}:{{WEBSITE_TAG}}
    env_file:
      - .env
    ports:
      - 3001:3000
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/etc/service-account.json}
    depends_on:
      - elasticsearch
    volumes:
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/elastic-search/lib:/service/lib
      - ../{{REPOSITORY_DIR}}/{{WEBSITE_REPO_NAME}}/elastic-search/index.js:/service/index.js
      - ../main-website-content-writer-key.json:/etc/service-account.json
    # command: bash -c "tail -f /dev/null"

  db:
    image: {{MYSQL_IMAGE_NAME}}:{{MYSQL_TAG}}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wordpress}
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 262114
        hard: 262114

  adminer:
    image: {{ADMINER_IMAGE_NAME}}:{{ADMINER_TAG}}
    ports:
      - ${ADMINER_HOST_PORT:-8080}:8080

volumes:
  db-data:
  uploads-data:
  wp-logs-data:
  es-data:
  backup-data: